### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by RichardoC** [ToxyBorg/llama_langchain_documents_embeddings#9]
Hi there, 

This repo is a great example of how to use these libraries. Mind adding an explicit license so I know whether I can use this code as examples?

Thanks

**Comment by ToxyBorg** [comment]
Yo! Thanks dude. I added an "Unlicense" license, so no restrictions 🖖.

Also, this repo/code is pretty old, so I hope you can adapt it to the new versions of Langchain
